source: "ahs"
raw_paths:
  admissions:           "/data/padmalab_external/special_project/AHS_Data_Release_2/rmt22884_dad_20211105.sas7bdat"
  ed:                   "/data/padmalab_external/special_project/AHS_Data_Release_2/rmt22884_ed_20211105.pickle"
  dad:                  "/data/padmalab_external/special_project/AHS_Data_Release_2/rmt22884_dad_20211105.pickle"
  ed_diagnoses_icd:     "/data/padmalab_external/special_project/AHS_Data_Release_2/rmt22884_ed_20211105.pickle"
  procedures_icd:       "/data/padmalab_external/special_project/AHS_Data_Release_2/rmt22884_dad_20211105.pickle"
  # labtests:             "/data/padmalab_external/special_project/AHS_Data_Release_2/"
  death:                "/data/padmalab_external/special_project/AHS_Data_Release_2/rmt22884_death_20251124.pickle"
  medicines:            "/data/padmalab_external/special_project/AHS_Data_Release_2/rmt22884_pin_20211105.sas7bdat"
  icu:                  "/data/padmalab_external/special_project/AHS_Data_Release_2/rmt22884_dad_20211105.pickle"
  ecg:                  "/data/padmalab_external/special_project/AHS_Data_Release_2/rmt22884_ecg_20211105_df.pickle"
  vital_status:         "/data/padmalab_external/special_project/AHS_Data_Release_2/rmt22884_vital_20211105.sas7bdat"
  registry:             "/data/padmalab_external/special_project/AHS_Data_Release_2/rmt22884_reg_20211105.sas7bdat"  
keys:
  subject_id: "PATID"
  # â‰ˆ: "episode_order"  
save_paths:
  meds_core: "/data/padmalab_external/special_project/MEDS-dataset/ahs_core.parquet"
  meds_plus: "/data/padmalab_external/special_project/MEDS-dataset/ahs_plus.parquet"